SELECT EXTRACT(YEAR FROM OS.SALES_DATE),
EXTRACT(MONTH FROM OS.SALES_DATE),
UI.GENDER,
COUNT(DISTINCT OS.USER_ID)
FROM ONLINE_SALE OS,
(
SELECT USER_ID, GENDER FROM USER_INFO
    WHERE GENDER IS NOT NULL
) UI
WHERE OS.USER_ID = UI.USER_ID
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE),
EXTRACT(MONTH FROM OS.SALES_DATE), UI.GENDER
ORDER BY EXTRACT(YEAR FROM OS.SALES_DATE),
EXTRACT(MONTH FROM OS.SALES_DATE),
UI.GENDER;