SELECT CCDP.CAR_ID, CCDP.CAR_TYPE, ROUND(DAILY_FEE * 30 * CCDP.DISCOUNT) AS FEE
FROM
(
    SELECT CC.CAR_ID, CC.CAR_TYPE, CC.DAILY_FEE, (1 - DP.DISCOUNT_RATE/100) AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_CAR CC,
        (
            SELECT CAR_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE IN ('세단', 'SUV')
            AND DURATION_TYPE = '30일 이상'
        ) DP
WHERE CC.CAR_TYPE = DP.CAR_TYPE) CCDP

WHERE CCDP.CAR_ID NOT IN
(
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (CAR_ID, END_DATE) IN
        (
            SELECT CAR_ID, MAX(END_DATE)
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            GROUP BY CAR_ID
        )
    AND TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221130'
    AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101'
)
    
AND ROUND(CCDP.DAILY_FEE * 30 * CCDP.DISCOUNT)
BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;