SELECT RH.CAR_ID, TMP.AVERAGE_DURATION
FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY RH,
(
    SELECT CAR_ID, ROUND(AVG(END_DATE - START_DATE + 1), 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) TMP
WHERE RH.CAR_ID = TMP.CAR_ID(+)
AND TMP.AVERAGE_DURATION >= 7
GROUP BY RH.CAR_ID, TMP.AVERAGE_DURATION
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
