-- 코드를 입력하세요
SELECT B.CAR_ID, B.AVERAGE_DURATION
FROM
(SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID) AS B
WHERE B.AVERAGE_DURATION >= 7
ORDER BY B.AVERAGE_DURATION DESC, B.CAR_ID DESC;