-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW RR, MEMBER_PROFILE MP
WHERE RR.MEMBER_ID =
(
    SELECT *
    FROM (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_TEXT) DESC
    )
    WHERE ROWNUM = 1
)
AND RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;