-- 코드를 작성해주세요
SELECT CASE WHEN MONTH(DIFFERENTIATION_DATE) IN (01, 02, 03) THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (04, 05, 06) THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (07, 08, 09) THEN '3Q'
        ELSE '4Q' END QUARTER,
COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY CASE WHEN MONTH(DIFFERENTIATION_DATE) IN (01, 02, 03) THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (04, 05, 06) THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (07, 08, 09) THEN '3Q'
        ELSE '4Q' END
ORDER BY QUARTER