SELECT
    CASE WHEN PRICE < 10000 THEN 0
    ELSE TRUNC(PRICE, -4) END AS PRICE_GROUP
    , COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY CASE WHEN PRICE < 10000 THEN 0
    ELSE TRUNC(PRICE, -4) END
    
ORDER BY PRICE_GROUP