SELECT 
    HISTORY_ID,
    ROUND((DAILY_FEE * (100 - NVL(DISCOUNT_RATE, 0)) /100) * PERIOD) AS FEE
FROM 
(
    SELECT 
        CAR.CAR_ID,
        CAR.CAR_TYPE,
        DAILY_FEE,
        HISTORY_ID,
        END_DATE - START_DATE + 1 AS PERIOD,
    CASE 
        WHEN 
            END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
        WHEN 
            END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
        WHEN 
            END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'
        ELSE 
            '7일 미만' 
    END AS DURATION_TYPE
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY,
        CAR_RENTAL_COMPANY_CAR CAR
    WHERE
        CAR.CAR_ID = HISTORY.CAR_ID
) PERIOD_TABLE,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
WHERE
    PERIOD_TABLE.CAR_TYPE = PLAN.CAR_TYPE(+)
AND
    PERIOD_TABLE.DURATION_TYPE = PLAN.DURATION_TYPE(+)
AND
    PERIOD_TABLE.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    HISTORY_ID DESC