-- 코드를 작성해주세요
SELECT SUM(C.CNT) AS FISH_COUNT
FROM (

SELECT COUNT(*) AS CNT
# SELECT A.FISH_TYPE, B.FISH_NAME
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME IN ('BASS', 'SNAPPER')
GROUP BY FISH_NAME) AS C