SELECT DISTINCT(RH.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH,
CAR_RENTAL_COMPANY_CAR C
WHERE RH.CAR_ID = C.CAR_ID
AND EXTRACT(MONTH FROM RH.START_DATE) = '10'
AND C.CAR_TYPE = '세단'
ORDER BY RH.CAR_ID DESC